"""
Simple Report Generator for Deepfake Detection Results
Creates basic text-based reports when PDF generation is not available.
"""

import os
from pathlib import Path
from typing import Dict, Optional
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

class SimpleReportGenerator:
    """Generate simple text-based reports for deepfake detection results."""

    def __init__(self):
        self.reports_dir = Path("reports")
        self.reports_dir.mkdir(exist_ok=True)

    def generate_report(self, result: Dict, report_path: Optional[str] = None,
                       visualization_dir: Optional[str] = None) -> str:
        """
        Generate a simple text report.

        Args:
            result: Detection result dictionary
            report_path: Path to save report
            visualization_dir: Directory with visualizations (not used in simple version)

        Returns:
            str: Path to generated report
        """
        if report_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"deepfake_report_{timestamp}.txt"
            report_path = str(self.reports_dir / filename)

        try:
            with open(report_path, 'w', encoding='utf-8') as f:
                self._write_report_header(f, result)
                self._write_detection_results(f, result)
                self._write_technical_details(f, result)
                self._write_footer(f)

            logger.info(f"Report generated: {report_path}")
            return report_path

        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
            return None

    def _write_report_header(self, f, result: Dict):
        """Write report header."""
        f.write("=" * 60 + "\n")
        f.write("DEEPFAKE DETECTION REPORT\n")
        f.write("=" * 60 + "\n\n")

        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"File: {result.get('file_name', 'Unknown')}\n")
        f.write(f"Type: {result.get('file_type', 'Unknown')}\n\n")

    def _write_detection_results(self, f, result: Dict):
        """Write detection results."""
        f.write("DETECTION RESULTS\n")
        f.write("-" * 30 + "\n")

        prediction = result.get('prediction', 'Unknown')
        confidence = result.get('confidence', 0)

        # Prediction with confidence level
        if confidence > 0.8:
            confidence_level = "[HIGH CONFIDENCE]"
        elif confidence > 0.6:
            confidence_level = "[MEDIUM CONFIDENCE]"
        else:
            confidence_level = "[LOW CONFIDENCE]"

        f.write(f"Prediction: {prediction}\n")
        f.write(f"Confidence: {confidence:.1%}\n")
        f.write(f"Confidence Level: {confidence_level}\n\n")

        # Probabilities
        probabilities = result.get('probabilities', {})
        if probabilities:
            f.write("Detailed Probabilities:\n")
            for label, prob in probabilities.items():
                f.write(f"  {label.title()}: {prob:.1%}\n")
            f.write("\n")

        # Interpretation
        if prediction == 'Real':
            if confidence > 0.8:
                interpretation = "[AUTHENTIC] The file appears to be authentic with high confidence."
            else:
                interpretation = "[CAUTION] The file appears to be authentic, but confidence is moderate."
        else:  # Fake
            if confidence > 0.8:
                interpretation = "[FAKE] The file is likely manipulated with high confidence."
            else:
                interpretation = "[CAUTION] The file may be manipulated, but confidence is moderate."

        f.write(f"Interpretation: {interpretation}\n\n")

    def _write_technical_details(self, f, result: Dict):
        """Write technical details."""
        f.write("TECHNICAL DETAILS\n")
        f.write("-" * 30 + "\n")

        f.write(f"Processing Time: {result.get('processing_time', 'N/A'):.2f} seconds\n")
        f.write(f"Device Used: {result.get('device', 'Unknown')}\n")

        # File-specific details
        if result.get('file_type') == 'video':
            frames = result.get('frames_processed', 'N/A')
            f.write(f"Frames Processed: {frames}\n")
        elif result.get('file_type') == 'audio':
            duration = result.get('duration', 'N/A')
            sample_rate = result.get('sample_rate', 'N/A')
            f.write(f"Duration: {duration:.2f} seconds\n")
            f.write(f"Sample Rate: {sample_rate} Hz\n")

        f.write("\n")

    def _write_footer(self, f):
        """Write report footer."""
        f.write("REPORT INFORMATION\n")
        f.write("-" * 30 + "\n")
        f.write("This report was generated by the Deepfake Detection System.\n")
        f.write("For more information, contact your system administrator.\n\n")

        f.write("IMPORTANT NOTICE\n")
        f.write("This analysis is based on AI model predictions and should be\n")
        f.write("verified by human experts for critical applications.\n")
        f.write("False positives and false negatives may occur.\n\n")

        f.write("=" * 60 + "\n")
        f.write("End of Report\n")